# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AocGo < Formula
  desc "CLI tool for managing and running Advent of Code solutions in Go"
  homepage "https://github.com/AnasImloul/aoc-go"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AnasImloul/aoc-go/releases/download/v0.1.8/aoc-go_0.1.8_darwin_amd64.tar.gz"
      sha256 "8c0c8ee8a86d5840d24e72e171732e2ddc11474259c8d3253c1c858d033ec46d"

      def install
        bin.install "aoc-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AnasImloul/aoc-go/releases/download/v0.1.8/aoc-go_0.1.8_darwin_arm64.tar.gz"
      sha256 "866fb82582ff861103663646043e1681e85289d7213117515d5399bc59411434"

      def install
        bin.install "aoc-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnasImloul/aoc-go/releases/download/v0.1.8/aoc-go_0.1.8_linux_amd64.tar.gz"
      sha256 "5ed5d0c844e890b40e1ff4f01b72d093f47e10e28342d0350a7bb57666f9b74e"
      def install
        bin.install "aoc-go"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnasImloul/aoc-go/releases/download/v0.1.8/aoc-go_0.1.8_linux_arm64.tar.gz"
      sha256 "1d08a6ce8f404d6232aaabedfc8caa475899415f3534a98d7301b6bc65ae0f57"
      def install
        bin.install "aoc-go"
      end
    end
  end

  test do
    system "#{bin}/aoc-go", "--version"
  end
end
