# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AocGo < Formula
  desc "CLI tool for managing and running Advent of Code solutions in Go"
  homepage "https://github.com/AnasImloul/aoc-go"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AnasImloul/aoc-go/releases/download/v0.2.4/aoc-go_0.2.4_darwin_amd64.tar.gz"
      sha256 "9fedccc8208b01c4c7a526b4dc2bd474fac64fb56564b529c1952bff5399793b"

      def install
        bin.install "aoc-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AnasImloul/aoc-go/releases/download/v0.2.4/aoc-go_0.2.4_darwin_arm64.tar.gz"
      sha256 "5b9b3e8f87ab99cd82e68df82a3739e5cc360a10212d5cda3114ecdb3ad98c00"

      def install
        bin.install "aoc-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnasImloul/aoc-go/releases/download/v0.2.4/aoc-go_0.2.4_linux_amd64.tar.gz"
      sha256 "df7f86d988b090eaf623726c93a2cc81cc74961664ff6023a15c1787c93eb0cb"
      def install
        bin.install "aoc-go"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnasImloul/aoc-go/releases/download/v0.2.4/aoc-go_0.2.4_linux_arm64.tar.gz"
      sha256 "c88493468bf906ddfb1cdbd1ff2e98e80bf0432c48abd7e846283cc2fee9cb2a"
      def install
        bin.install "aoc-go"
      end
    end
  end

  test do
    system "#{bin}/aoc-go", "--version"
  end
end
