# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AocGo < Formula
  desc "CLI tool for managing and running Advent of Code solutions in Go"
  homepage "https://github.com/AnasImloul/aoc-go"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AnasImloul/aoc-go/releases/download/v0.1.6/aoc-go_0.1.6_darwin_amd64.tar.gz"
      sha256 "6fa7f13a9e97fd968c39d9b38490ddcf9fa0e34d333f925c88dd082806ba03ad"

      def install
        bin.install "aoc-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AnasImloul/aoc-go/releases/download/v0.1.6/aoc-go_0.1.6_darwin_arm64.tar.gz"
      sha256 "628617ce2a0782b8e9d1bcdfbc1f2af745424f13a27b36ff5abc696a69f6569c"

      def install
        bin.install "aoc-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnasImloul/aoc-go/releases/download/v0.1.6/aoc-go_0.1.6_linux_amd64.tar.gz"
      sha256 "d9a0104c99b9ea1020e05f32a1bc73ab40a0cfb7f544dc706414164cfcd4dd57"
      def install
        bin.install "aoc-go"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnasImloul/aoc-go/releases/download/v0.1.6/aoc-go_0.1.6_linux_arm64.tar.gz"
      sha256 "49cd1006c64c80d40954d04911b45c7006492e1b8138dc9291f15fa05dff5882"
      def install
        bin.install "aoc-go"
      end
    end
  end

  test do
    system "#{bin}/aoc-go", "--version"
  end
end
